version: '2'
services:
      server:
        build: ./
        ports: 
          - 8080:8080
        depends_on:
          - mongodb
        environment:
          WAIT_HOSTS: redis:6379, mongodb:27017

      ws_server:
        build: ./go_back/
        container_name: "golang"
        ports:
          - 8081:8081
        environment:
          WAIT_HOSTS: redis:6379, mongodb:27017
        depends_on:
          - redis

      mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGODB_USER="user" 
          - MONGODB_PASS="pass"
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod

      redis:
        image: redis:latest
        container_name: "redis"
        ports:
          - 6379:6379
    
      nginx:
        image: nginx:latest
        container_name: "nginx"
        ports: 
          - 8885:8885
        volumes:
          - ./nginx/my.conf:/etc/nginx/conf.d/my.conf
        links:
          - server
          - ws_server
        depends_on:
            - server
            - ws_server
