version: '2'
services:
      server:
        build: ./
        command: python3 app.py
        ports: 
          - 8080:8080
        depends_on:
            - mongodb
      mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGODB_USER="user" 
          - MONGODB_PASS="pass"
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod 
