version: '2'
services:
      server:
        build: ./
        ports: 
          - 8080:8080

      ws_server:
        build: ./microservices/go_back/
        container_name: "golang"
        ports:
          - 8081:8081
